on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: "enter new release branch"
        required: true
jobs:
  create-new-release-branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.tag }}'
          fetch-depth: 0
      - name: Check format of new release branch
        env:
          BRANCH: ${{ github.event.inputs.release_branch_name }}
        run: |
          set -e
          . .githooks/common.bash
          $(check_format_release_branch "${BRANCH}")
      - name: Prepare new release branch
        id: prepare_new_release_branch
        run: |
          echo "::set-output name=NEW_BRANCH::demo_test/$(date --date="next Wednesday" '+%Y%m%d')"
      - name: Get current release branch
        id: current_release_branch
        run: |
          echo "::set-output name=BRANCH_NAME::release/$(date --date="this Wednesday" '+%Y%m%d')"
      - name: Get all PR of old release branch
        uses: actions/github-script@v4
        with: 
          script: |
            const url = `/repos/${{ github.repository }}/pulls?per_page=100`
            const result = await github.request(url)
            console.log(result)