on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: "enter new release branch (e.g. release/20211231)"
        required: true
jobs:
  create-new-release-branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check format of new release branch
        env:
          BRANCH: ${{ github.event.inputs.release_branch_name }}
        run: |
          check_format_release_branch() {
            regexp_release_branch="release\/(20[2-9][1-9])(1[0-2]|0[1-9])(3[01]|[0-2][1-9]|[12]0)"
            branch="$1"
            match_count=$(echo ${branch} | grep -o -P "${regexp_release_branch}" | wc -l)
            if [[ ${match_count} != 1 ]]; then
              >&2 echo "ERROR: release branch is not properly formatted (got \"${branch}\", expected \"release/yyyymmdd\")"; return 1
            fi
            return 0
          }
          $(check_format_release_branch "${BRANCH}")

      - name: Get current release branch
        id: current_release_branch
        run: |
          set -e
          git branch --all --list 'remote/origin/release/20*' | sort -r | head -n 1 | cut -c18-
          echo "::set-output name=BRANCH_NAME::$(git branch --all --list 'remote/origin/release/20*' | sort -r | head -n 1 | cut -c18-)"

      - name: Get all PR of old release branch
        uses: actions/github-script@v4
        id: get_pull_request_numbers
        env:
          REPO: ${{ github.repository }}
          CURRENT_RELEASE_BRANCH: ${{ steps.current_release_branch.outputs.BRANCH_NAME }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getListPRNumber } = require(`${{github.workspace}}/.github/workflows/create_new_release.js`)
            return getListPRNumber(github)

      - name: Create a request change for old pull requests
        uses: actions/github-script@v4
        env:
          REPO: ${{ github.repository }}
          NEW_RELEASE_BRANCH: ${{ github.event.inputs.release_branch_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const listPRNumber = ${{ steps.get_pull_request_numbers.outputs.result }}
            const { requestChange } = require(`${{github.workspace}}/.github/workflows/create_new_release.js`)
            return requestChange(github, listPRNumber)

      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.event.inputs.release_branch_name }}
