name: Create change log
on:
  workflow_dispatch:
jobs:
  create_change_log:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current release branch
        id: current_release_branch
        run: |
          set -e
          echo "::set-output name=BRANCH_NAME::$(git branch --all --list '*release/20*' | sort -r | head -n 1 | cut -c18-)"

      - name: Get release PR
        uses: actions/github-script@v4
        id: get_release_pull_request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {getReleasePR} = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            return await getReleasePR({github,context}, `${{ steps.current_release_branch.outputs.BRANCH_NAME }}`)
          
      - name: Get all PR that has base is current release branch
        uses: actions/github-script@v4
        id: get_all_pr_has_base_is_current_release_branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getListMergedPR } = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            return await getListMergedPR({github,context}, `${{ steps.current_release_branch.outputs.BRANCH_NAME }}`)

      - name: Find all subtask related to each PR
        uses: actions/github-script@v4
        id: find_all_subtask_for_each_pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {getSubtaskForEachPR} = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            return await getSubtaskForEachPR({github,context}, ${{ steps.get_all_pr_has_base_is_current_release_branch.outputs.result }})

      - name: Update current PR description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {updateCurrentPRDescription} = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            await updateCurrentPRDescription({github,context}, ${{ steps.get_release_pull_request.outputs.result }}, ${{ steps.find_all_subtask_for_each_pr.outputs.result }})