on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: "enter new release branch"
        required: true
jobs:
  create-new-release-branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.tag }}'
          fetch-depth: 0
      - name: Check format of new release branch
        env:
          BRANCH: ${{ github.event.inputs.release_branch_name }}
        run: |
          check_format_release_branch() {
            regexp_release_branch="release\/(20[2-9][1-9])(1[0-2]|0[1-9])(3[01]|[0-2][1-9]|[12]0)"
            branch="$1"
            match_count=$(echo ${branch} | grep -o -P "${regexp_release_branch}" | wc -l)
            if [[ ${match_count} != 1 ]]; then
              >&2 echo "ERROR: release branch is not formatted"; return 1
            fi
            return 0
          }
          $(check_format_release_branch "${BRANCH}")
      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.event.inputs.release_branch_name }}
      - name: Get current release branch
        id: current_release_branch
        run: |
          echo "::set-output name=BRANCH_NAME::release/$(date --date="this Wednesday" '+%Y%m%d')"
      - name: Get all PR of old release branch
        uses: actions/github-script@v4
        id: get_pull_request_numbers
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let listPRNumber = []
            let limit = 100
            let page = 1
            let url = `/repos/${{ github.repository }}/pulls?per_page=${ limit }&page=${ page }&base=${{ steps.current_release_branch.outputs.BRANCH_NAME }}`
            let result = await github.request(url)
            console.log(result) // for the reviewer, they can see what is in response, I wil remove this line before merge
            let dataSize = 0

            while (result.data.length != 0) {
              dataSize = result.data.length
              for (let i=0; i < dataSize; i++) {
                listPRNumber.push(result.data[i].number)
              }
              if (dataSize < limit) {
                break
              }
              page++
              url = `/repos/${{ github.repository }}/pulls?per_page=${ limit }&page=${ page }&base=${{ steps.current_release_branch.outputs.BRANCH_NAME }}`
              result = await github.request(url)
              console.log(result) // for the reviewer, they can see what is in response, I wil remove this line before merge
            }
            return listPRNumber
      - name: Create a request change for old pull requests
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let listPRNumber = ${{ steps.get_pull_request_numbers.outputs.result }}
            let requests = []
            const totalPR = listPRNumber.length
            let url = ""
            for (let i=0;i<totalPR;i++) {
              url = `POST /repos/${{ github.repository }}/pulls/${ listPRNumber[i] }/reviews`
              requests.push(github.request(url, {
                event: "REQUEST_CHANGES",
                body: `Your current release branch is outdated. You must update your PR's base branch to the new release branch ${{ github.event.inputs.release_branch_name }}`
              }))
            }

            let responses = await Promise.all(requests)
            console.log(responses) // for the reviewer, they can see what is in response, I wil remove this line before merge
        