on:
  workflow_dispatch:
jobs:
  create_change_log:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current release branch
        id: current_release_branch
        run: |
          set -e
          echo "::set-output name=BRANCH_NAME::$(git branch --all --list '*release/20*' | sort -r | head -n 1 | cut -c18-)"

      - name: Get release pull request
        uses: actions/github-script@v4
        id: get_release_pull_request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `/repos/${{ github.repository }}/pulls?base=develop&head=${{ steps.current_release_branch.outputs.BRANCH_NAME }}`
            const result = await github.request(url)
            console.log(result)
            if (result.data.length != 0) {
              return result.data[0].number
            }
            return 0
          
      - name: Get all PR that has base is current release branch
        uses: actions/github-script@v4
        id: get_all_pr_has_base_is_current_release_branch
        env:
          REPO: ${{ github.repository }}
          CURRENT_RELEASE_BRANCH: ${{ steps.current_release_branch.outputs.BRANCH_NAME }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getListMergedPR } = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            return await getListMergedPR(github)

      - name: Find all subtask related to each PR
        uses: actions/github-script@v4
        id: find_all_subtask_for_each_pr
        env:
          REPO: ${{ github.repository }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {getSubtaskForEachPR} = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            let result = await getSubtaskForEachPR(github, ${{ steps.get_all_pr_has_base_is_current_release_branch.outputs.result }})
            console.log(result)
            return result

      - name: Update current PR description
        uses: actions/github-script@v4
        env:
          REPO: ${{ github.repository }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {updateCurrentPRDescription} = require(`${{github.workspace}}/.github/workflows/create_change_log.js`)
            await updateCurrentPRDescription(github, ${{ steps.get_release_pull_request.outputs.result }}, ${{ steps.find_all_subtask_for_each_pr.outputs.result }})